### ISSUE TITLE
Where in the world is Cilium values? 🔎

### ISSUE THREAD

**Issue by jahanson** [bjw-s/home-ops#4949]
https://github.com/bjw-s/home-ops/blob/1f33c1c8883274e6daeec2626c769992521766f3/infrastructure/talos/cluster-0/deploy-integrations.sh#L6

**Comment by bjw-s** [comment]
https://github.com/bjw-s/home-ops/blob/main/kubernetes/cluster-0/apps/kube-system/cilium/app/values.yaml

**Comment by jahanson** [comment]
I legitimately don't know why I couldn't find it. Mark this up to not having enough coffee yet 😅 .
