### ISSUE TITLE
mosquitto is not saving its db to your storage

### ISSUE THREAD

**Issue by LucaDev** [bjw-s/home-ops#5403]
I just had a look at your mosquitto deployment to get some inspiration on how to set it up for me and came by this: 

https://github.com/bjw-s/home-ops/blob/0ad2fe41564d11d4c7f04d9b5d36ae2d52cb9c11/kubernetes/cluster-0/apps/home-automation/mosquitto/app/helmrelease.yaml#L83
vs
https://github.com/bjw-s/home-ops/blob/0ad2fe41564d11d4c7f04d9b5d36ae2d52cb9c11/kubernetes/cluster-0/apps/home-automation/mosquitto/app/config/mosquitto.conf#L5

It looks like you're trying to make it persist the values but you're either mounting the volume to the wrong directory or setting the wrong dir in the mosquitto conf. 

But I also might be mistaken here and just don't understand whats going on. In that case: Sorry - please ignore this ^^

**Comment by bjw-s** [comment]
Thank you for pointing this out to me! I will definitely check this out when I'm back from my work trip :)
